# Generated by Django 4.2 on 2023-04-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_title_rating_alter_review_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date']},
        ),
    ]
